### ISSUE TITLE
Flere norske offentlige designsystemer

### ISSUE THREAD

**Issue by pudderland** [siiron/norwegian-design-systems#47]
Sikt: https://designsystem.sikt.no/
IMDi: https://design.imdi.no/
SSB: https://design.ssb.no/#/
Politiet: https://www.politiet.no/design/brukeropplevelse/
Helsenorge: https://github.com/helsenorge/designsystem

**Comment by siiron** [comment]
Takk, ser ut som jeg har alle på listen https://github.com/siiron/norwegian-design-systems :-)
