### ISSUE TITLE
3 designsystemer som ikke er i listen

### ISSUE THREAD

**Issue by idalower** [siiron/norwegian-design-systems#9]
Forslag til designsystemer til listen:

https://designmanual.norgesnasjonalparker.no/ (norges nasjonalparker)
http://nt-designguide.no/mormerket/ (norsk tipping)
https://company-139306.frontify.com/d/YokG7g2Ch3dy/brand (innovasjon norge)

**Comment by siiron** [comment]
Takk for bidrag @idalower 🥇
